import test from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdtemp, rm, mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createOliviaService } from '../server.js';
import { writeModelProfile, setActiveProvider, readModelConfig } from '../model-config.js';
const browserTest=process.env.OLIVIA_BROWSER_UI==='1'?test:test.skip;
browserTest('manual model survives failed discovery and saves; candidate selection updates the submitted model',async t=>{
  const {chromium}=createRequire(import.meta.url)('playwright');
  const root=await mkdtemp(join(tmpdir(),'olivia-relay-ui-'));
  let allowDiscovery=false;const sent=[];
  const profile={provider:'local',baseUrl:'https://relay.fixture/v1',model:'old-model',authMode:'bearer',apiKey:'fixture-key'};
  await writeModelProfile({root,provider:'local',profile});await setActiveProvider({root,provider:'local'});
  const service=await createOliviaService({root,dataDir:join(root,'data'),appData:join(root,'appdata'),worker:false,runMemoryRefresh:false,fetch:async(url,init)=>{
    assert.equal(new URL(url).origin,'https://relay.fixture');
    if(url.endsWith('/models'))return allowDiscovery?Response.json({data:[{id:'candidate-model'}]}):Response.json({error:{message:'not supported'}},{status:404});
    sent.push(JSON.parse(init.body));return Response.json({choices:[{message:{content:'OK'}}]});
  }});
  const address=await service.listen(0);const base=`http://127.0.0.1:${address.port}`;
  const browser=await chromium.launch({channel:'msedge',headless:true});
  t.after(async()=>{await browser.close();await service.close();await rm(root,{recursive:true,force:true});});
  const page=await browser.newPage({viewport:{width:1024,height:900}});page.setDefaultTimeout(5000);
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/*',route=>new URL(route.request().url()).origin===base?route.continue():route.abort());
  await page.goto(base+'/admin/');
  await page.waitForFunction(()=>document.querySelector('#localModelBaseUrl')?.value==='https://relay.fixture/v1');
  await page.locator('.sideTab[data-tab="ai"]').click();
  assert.equal(await page.locator('#localModelName').evaluate(el=>el.tagName),'INPUT');
  await page.locator('#localModelName').fill('manual-only-model');
  await page.locator('#queryLocalModels').click();
  await page.waitForFunction(()=>document.querySelector('#localModelResult').textContent.includes('查询失败'));
  if(await page.locator('#noticeLayer').isVisible())await page.locator('#noticeConfirm').click();
  assert.equal(await page.locator('#localModelName').inputValue(),'manual-only-model');
  await page.locator('#testLocalModel').click();
  await page.waitForFunction(()=>document.querySelector('#localModelResult').textContent.includes('配置已保存'));
  assert.equal((await readModelConfig({root})).profiles.local.model,'manual-only-model');
  assert.equal(sent.at(-1).model,'manual-only-model');
  allowDiscovery=true;
  await page.locator('#queryLocalModels').click();
  await page.waitForFunction(()=>document.querySelector('#localModelResult').textContent.includes('已查询'));
  assert.equal(await page.locator('#localModelName').inputValue(),'manual-only-model');
  await page.locator('#localModelNameOptions').selectOption('candidate-model');
  assert.equal(await page.locator('#localModelName').inputValue(),'candidate-model');
  await page.locator('#testLocalModel').click();
  await page.waitForFunction(()=>document.querySelector('#localModelResult').textContent.includes('配置已保存'));
  assert.equal((await readModelConfig({root})).profiles.local.model,'candidate-model');
  assert.deepEqual(errors,[]);
  if(process.env.OLIVIA_BROWSER_SCREENSHOT_DIR){await mkdir(process.env.OLIVIA_BROWSER_SCREENSHOT_DIR,{recursive:true});await page.screenshot({path:join(process.env.OLIVIA_BROWSER_SCREENSHOT_DIR,'relay-settings.png'),fullPage:true});}
});
